# Generated by Django 4.1.5 on 2023-01-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_student_course"
            ),
        ),
    ]
