# Generated by Django 4.1.5 on 2023-01-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple", "0002_character_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="characters",
        ),
        migrations.DeleteModel(
            name="Character",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
