# Generated by Django 4.1.5 on 2023-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple", "0003_remove_movie_characters_delete_character_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "movies",
                    models.ManyToManyField(to="simple.movie", verbose_name="Movies"),
                ),
            ],
        ),
    ]
